# Generated by Django 3.2.6 on 2021-11-23 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cli_rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cli_nombre', models.CharField(max_length=50)),
                ('cli_direccion', models.CharField(max_length=50)),
                ('cli_fono', models.IntegerField()),
                ('cli_correo', models.CharField(max_length=30)),
                ('cli_contra', models.CharField(max_length=24)),
                ('cli_admin', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('com_id', models.IntegerField(primary_key=True, serialize=False)),
                ('com_nroBoleta', models.IntegerField()),
                ('com_fecha', models.DateField()),
                ('com_direccionEnvio', models.CharField(max_length=50)),
                ('com_enviada', models.BooleanField()),
                ('com_recibido', models.BooleanField()),
                ('com_retiroTienda', models.BooleanField()),
                ('com_recargo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_compra',
            fields=[
                ('com_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pro_sku', models.CharField(max_length=15)),
                ('det_com_cantidad', models.IntegerField()),
                ('det_com_precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('pro_sku', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('pro_nombre', models.CharField(max_length=20)),
                ('pro_precio', models.IntegerField()),
                ('pro_talla', models.CharField(max_length=3)),
                ('pro_comentario', models.CharField(max_length=40)),
                ('pro_categoria', models.CharField(max_length=50)),
                ('pro_disponibilidad', models.BooleanField()),
                ('pro_stock', models.IntegerField()),
            ],
        ),
    ]
