# Generated by Django 3.2.6 on 2021-11-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendita', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cli_admin',
        ),
        migrations.AddField(
            model_name='cliente',
            name='cli_apellido',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
