# Generated by Django 3.2.6 on 2021-11-29 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendita', '0002_auto_20211128_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cli_direccion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
