# Generated by Django 3.2.6 on 2021-12-03 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiendita', '0003_alter_cliente_cli_direccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('per_rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('per_nombre', models.CharField(max_length=50)),
                ('per_apellido', models.CharField(max_length=50)),
                ('per_correo', models.CharField(max_length=30)),
                ('per_contra', models.CharField(max_length=24)),
            ],
            options={
                'verbose_name': 'Admin',
                'verbose_name_plural': 'Admins',
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('per_rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('per_nombre', models.CharField(max_length=50)),
                ('per_apellido', models.CharField(max_length=50)),
                ('per_correo', models.CharField(max_length=30)),
                ('per_contra', models.CharField(max_length=24)),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
            },
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='compra',
            options={'verbose_name': 'Compra', 'verbose_name_plural': 'Compras'},
        ),
        migrations.AlterModelOptions(
            name='detalle_compra',
            options={'verbose_name': 'Detalle Compra', 'verbose_name_plural': 'Detalles Compra'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='cli_apellido',
            new_name='per_apellido',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='cli_contra',
            new_name='per_contra',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='cli_correo',
            new_name='per_correo',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='cli_nombre',
            new_name='per_nombre',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='cli_rut',
            new_name='per_rut',
        ),
        migrations.AddField(
            model_name='compra',
            name='com_cliente',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.RESTRICT, to='tiendita.cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compra',
            name='com_detalles',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.RESTRICT, to='tiendita.detalle_compra'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detalle_compra',
            name='det_com_producto',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.RESTRICT, to='tiendita.producto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cli_direccion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='com_enviada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='compra',
            name='com_recargo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='compra',
            name='com_recibido',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='compra',
            name='com_retiroTienda',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='pro_categoria',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='pro_comentario',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='pro_talla',
            field=models.CharField(choices=[('XS', 'Muy pequeño'), ('S', 'Pequeño'), ('M', 'Mediano'), ('L', 'Grande'), ('XL', 'Extra Grande'), ('TU', 'Talla unica')], default='TU', max_length=3),
        ),
    ]
