# Generated by Django 3.2.6 on 2021-12-04 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendita', '0004_auto_20211203_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='pro_imagen',
            field=models.ImageField(default=2, upload_to='fotos'),
            preserve_default=False,
        ),
    ]
