# Generated by Django 3.2.6 on 2021-12-04 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendita', '0005_producto_pro_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='pro_marca',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
    ]
